### ISSUE TITLE
need help and take a lot of time

### ISSUE THREAD

**Issue by LendisFabri** [ibnujakaria/deteksi-penyakit-jagung#2]
oh come on i'm waiting for you

**Comment by ibnujakaria** [comment]
mas anda ngapain bikin issue di tempat saya? :astonished:

**Comment by LendisFabri** [comment]
Mas ini bisa diinstall di OS saya yang superiorr itu??

**Comment by ibnujakaria** [comment]
Secara teori bisa mas....
